/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gateway_prot.h"

bool_t
xdr_bamboo_stat (XDR *xdrs, bamboo_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_key (XDR *xdrs, bamboo_key objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_value (XDR *xdrs, bamboo_value *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->bamboo_value_val, (u_int *) &objp->bamboo_value_len, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_placemark (XDR *xdrs, bamboo_placemark *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->bamboo_placemark_val, (u_int *) &objp->bamboo_placemark_len, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_value_hash (XDR *xdrs, bamboo_value_hash objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_hash (XDR *xdrs, bamboo_hash *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->algorithm, 20))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->hash.hash_val, (u_int *) &objp->hash.hash_len, 40))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_put_arguments (XDR *xdrs, bamboo_put_arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->application, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_library, 255))
		 return FALSE;
	 if (!xdr_bamboo_key (xdrs, objp->key))
		 return FALSE;
	 if (!xdr_bamboo_value (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_bamboo_hash (xdrs, &objp->secret_hash))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl_sec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_get_args (XDR *xdrs, bamboo_get_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->application, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_library, 255))
		 return FALSE;
	 if (!xdr_bamboo_key (xdrs, objp->key))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxvals))
		 return FALSE;
	 if (!xdr_bamboo_placemark (xdrs, &objp->placemark))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_get_value (XDR *xdrs, bamboo_get_value *objp)
{
	register int32_t *buf;

	 if (!xdr_bamboo_value (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl_sec_rem))
		 return FALSE;
	 if (!xdr_bamboo_hash (xdrs, &objp->secret_hash))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_get_result (XDR *xdrs, bamboo_get_result *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (bamboo_get_value), (xdrproc_t) xdr_bamboo_get_value))
		 return FALSE;
	 if (!xdr_bamboo_placemark (xdrs, &objp->placemark))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_rm_arguments (XDR *xdrs, bamboo_rm_arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->application, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_library, 255))
		 return FALSE;
	 if (!xdr_bamboo_key (xdrs, objp->key))
		 return FALSE;
	 if (!xdr_bamboo_hash (xdrs, &objp->value_hash))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->secret_hash_alg, 20))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->secret.secret_val, (u_int *) &objp->secret.secret_len, 40))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl_sec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_put_args (XDR *xdrs, bamboo_put_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->application, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_library, 255))
		 return FALSE;
	 if (!xdr_bamboo_key (xdrs, objp->key))
		 return FALSE;
	 if (!xdr_bamboo_value (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl_sec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_get_res (XDR *xdrs, bamboo_get_res *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->values.values_val, (u_int *) &objp->values.values_len, ~0,
		sizeof (bamboo_value), (xdrproc_t) xdr_bamboo_value))
		 return FALSE;
	 if (!xdr_bamboo_placemark (xdrs, &objp->placemark))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bamboo_rm_args (XDR *xdrs, bamboo_rm_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->application, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->client_library, 255))
		 return FALSE;
	 if (!xdr_bamboo_key (xdrs, objp->key))
		 return FALSE;
	 if (!xdr_bamboo_value_hash (xdrs, objp->value_hash))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl_sec))
		 return FALSE;
	return TRUE;
}
